groups:

  - alert: InstanceDown
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} is down"

  - name: test_alert
    rules:
      - alert: TestAlert
        expr: vector(1)
        for: 20s
        labels:
          severity: critical
        annotations:
          summary: "ðŸ§ª Test Alert"
          description: >
            This is a test simple alert to verify that email notifications work ðŸ¤ª.
            I wish you have a wonderful day ðŸ˜˜

  - name: container_cpu_alert
    rules:
      - alert: HighContainerCPUUsage
        expr: rate(container_cpu_usage_seconds_total[3m]) * 100 > 80
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "ðŸš’ High CPU usage detected on container {{ $labels.container }} "
          description: >
            CPU usage has been above 80% for the last 3 minutes.
            Please investigate the container: {{ $labels.container }} ðŸ§¯!


  - name: container_memory_alert
    rules:
      - alert: HighContainerMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 80
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "ðŸš’ High Memory usage detected on container {{ $labels.container }}"
          description: >
            Memory usage has been above 80% for the last 3 minutes.
            Please check the container: {{ $labels.container }} ðŸ§¯!

  - name: container_disk_alert
    rules:
      - alert: HighContainerDiskIO
        expr: rate(container_fs_io_time_seconds_total[5m]) > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "âš ï¸ High Disk I/O detected on container {{ $labels.container }}"
          description: >
            The disk I/O usage has been high for the last 5 minutes.
            Investigate possible performance issues.

  - name: container_network_alert
    rules:
      - alert: HighNetworkTraffic
        expr: rate(container_network_transmit_bytes_total[5m]) > 100000000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "âš ï¸ High network traffic detected on container {{ $labels.container }}"
          description: >
            The network traffic has exceeded 100MB per second for the last 5 minutes.
            Please check if it's expected behavior.
